name: CI Workflow

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile C++ code
        run: g++ stack.cpp -o main

      - name: Run the program
        run: ./main
